In [1]:
import numpy as np

In [15]:
#xor combination

x = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

np.random.seed(1)

In [26]:
#random initialize weight with mean 0
w0 = 2*np.random.random((3,4))-1
w1 = 2*np.random.random((4,1))-1


In [27]:
print(w0)

[[-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043]]


In [28]:
print(w1)

[[-0.66033916]
 [ 0.75628501]
 [-0.80330633]
 [-0.15778475]]


In [29]:
#sigmoid ctivtion function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    
    return 1/(1+np.exp(-x))

In [30]:
#train the network
for j in range(6000):
        #feed forward
        layer0 = x #input layer
        layer1 = nonlin(np.dot(layer0,w0)) #weight and input matrix multiply. dot product
        layer2 = nonlin(np.dot(layer1,w1))
        
        #calculate the error
        layer2_error = y-layer2
        if(j%1000)==0:
            print("ERROR: "+str(np.mean(np.abs(layer2_error))))
        
        #Back propagation of error using the chain rule 
        layer2_delta = layer2_error*nonlin(layer2,deriv=True)
        layer1_error = layer2_delta.dot(w1.T)
        layer1_delta = layer1_error*nonlin(layer1,deriv=True)
        
        #gradient descent error optimizer
        w1 += layer1.T.dot(layer2_delta)*.1
        w0 += layer0.T.dot(layer1_delta)*.1

ERROR: 0.4981430639509009
ERROR: 0.48131179303972504
ERROR: 0.39984844949607157
ERROR: 0.20839084695506066
ERROR: 0.1198765495563402
ERROR: 0.08761840473348703
