In [2]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [3]:
train_labels = []
train_samples = []

In [17]:
for i in range(1000):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    random_order = randint(65,100)
    train_samples.append(random_order)
    train_labels.append(1)
    
for i in range(50):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    random_order = randint(65,100)
    train_samples.append(random_order)
    train_labels.append(0)

In [22]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)

In [23]:
train_labels


array([0, 1, 0, ..., 0, 1, 0])

In [24]:
scaler = MinMaxScaler(feature_range=(0,1))

In [25]:
scaler

MinMaxScaler(copy=True, feature_range=(0, 1))

In [26]:
scaler.fit_transform((train_samples).reshape(-1,1))

/home/sakib/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.12643678],
       [0.86206897],
       [0.50574713],
       ...,
       [0.94252874],
       [0.27586207],
       [0.72413793]])

In [27]:
(train_samples).reshape(-1,1)

array([[24],
       [88],
       [57],
       ...,
       [95],
       [37],
       [76]])