In [1]:
#import all necessary liberty

%matplotlib inline
#import matplotlib.pyplot as plt
from matplotlib import pyplot as plt
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix

import pandas as pd

#missing value handle
from sklearn.preprocessing import Imputer


#from sklearn.preprocessing import Imputer
#import impute.SimpleImputer from sklearn
#import impute.SimpleImputer from sklearn

#To shuffle the data set
from sklearn.utils import shuffle

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Activation
from keras.layers import Dropout
from keras.optimizers import SGD
from keras.optimizers import Adam
#from sklearn.utils import shuffle
import csv

#spliting dataset into traning set and test set
from sklearn.model_selection import train_test_split
import itertools
import sys

Using TensorFlow backend.


In [2]:
#import csv data_set

data_frame = pd.read_csv('./data-withoutapp_v2_clean_ecg.csv',na_values=['NA','?'])
#data_frame = pd.read_csv('./data-withoutapp.csv')
df=data_frame

data_frame.shape

(835, 15)

In [66]:
data_frame.columns

Index(['Age', 'Sex', 'Smoking', 'HTN', 'DLP', 'DM', 'Physical Exercise',
       'Family History', 'Drug History', 'Psychological Stress', 'Chest Pain',
       'Dyspnea', 'Palpitation', 'ECG', 'IHD-HeartAttack'],
      dtype='object')

In [3]:
data_frame.head(3)

Age   Sex Smoking  HTN DLP   DM Physical Exercise Family History  \
0  65.0  Male      no  yes  no  yes                no             no   
1  48.0  Male      no  yes  no  yes                no             no   
2  80.0  Male      ex  yes  no  yes               yes             no   

  Drug History Psychological Stress Chest Pain Dyspnea Palpitation       ECG  \
0          yes                   no        yes      no          no  abnormal   
1          yes                   no        yes      no          no  abnormal   
2          yes                   no         no      no          no  abnormal   

  IHD-HeartAttack  
0             Yes  
1             Yes  
2             Yes

In [4]:
data_frame.isnull().sum()

Age                      4
Sex                      1
Smoking                  3
HTN                      3
DLP                      8
DM                       1
Physical Exercise        9
Family History           7
Drug History            28
Psychological Stress    15
Chest Pain               3
Dyspnea                  2
Palpitation              5
ECG                     36
IHD-HeartAttack          0
dtype: int64

In [5]:
data_frame.shape

(835, 15)

In [6]:
data_frame.head()

Age   Sex Smoking  HTN DLP   DM Physical Exercise Family History  \
0  65.0  Male      no  yes  no  yes                no             no   
1  48.0  Male      no  yes  no  yes                no             no   
2  80.0  Male      ex  yes  no  yes               yes             no   
3  67.0  Male     yes  yes  no   no                no             no   
4  55.0  Male     yes  yes  no   no                no             no   

  Drug History Psychological Stress Chest Pain Dyspnea Palpitation       ECG  \
0          yes                   no        yes      no          no  abnormal   
1          yes                   no        yes      no          no  abnormal   
2          yes                   no         no      no          no  abnormal   
3          yes                   no        yes     yes          no  abnormal   
4           no                   no        yes     yes          no  abnormal   

  IHD-HeartAttack  
0             Yes  
1             Yes  
2             Yes  
3             Yes  
4             Yes

In [7]:
data_frame.Age.fillna(df['Age'].mean(),inplace=True)

In [8]:
data_frame['IHD-HeartAttack'].value_counts(dropna=False)

Yes    511
No     324
Name: IHD-HeartAttack, dtype: int64

In [9]:
#15
#Mapping the "output" values
map_output = {"Yes" : 1, "No" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['IHD-HeartAttack']	=	data_frame['IHD-HeartAttack'].map(map_output)

#data_frame['IHD-HeartAttack']

In [10]:
data_frame['IHD-HeartAttack'].value_counts(dropna=False)

1    511
0    324
Name: IHD-HeartAttack, dtype: int64

In [11]:
data_frame['Sex'].value_counts(dropna=False)

Male      638
Female    196
NaN         1
Name: Sex, dtype: int64

In [12]:
#2
#Mapping "gender" feature
map_output = {"Male" : 1, "Female" : 2,None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Sex']	=	data_frame['Sex'].map(map_output)

#data_frame['Sex']

In [13]:
data_frame['Sex'].value_counts(dropna=False)

 1     638
 2     196
-20      1
Name: Sex, dtype: int64

In [14]:
data_frame['Smoking'].value_counts(dropna=False)

no     502
yes    245
ex      85
NaN      3
Name: Smoking, dtype: int64

In [15]:
#3
#Mapping "Smoking" feature
map_output = {"yes" : 1, "no" : 0, "ex" : 2, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Smoking']	=	data_frame['Smoking'].map(map_output)

#data_frame['Smoking']

In [16]:
data_frame['Smoking'].value_counts(dropna=False)

 0     502
 1     245
 2      85
-20      3
Name: Smoking, dtype: int64

In [17]:
data_frame['HTN'].value_counts(dropna=False)

yes    461
no     371
NaN      3
Name: HTN, dtype: int64

In [18]:
#4
#Mapping "HTN" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['HTN']	=	data_frame['HTN'].map(map_output)

#data_frame['HTN']

In [19]:
data_frame['HTN'].value_counts(dropna=False)

 1     461
 0     371
-20      3
Name: HTN, dtype: int64

In [20]:
data_frame['DLP'].value_counts(dropna=False)

no     739
yes     88
NaN      8
Name: DLP, dtype: int64

In [21]:
#5
#Mapping "DLP" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['DLP']	=	data_frame['DLP'].map(map_output)

#data_frame['DLP']

In [22]:
data_frame['DLP'].value_counts(dropna=False)

 0     739
 1      88
-20      8
Name: DLP, dtype: int64

In [23]:
data_frame['DM'].value_counts(dropna=False)

no     551
yes    283
NaN      1
Name: DM, dtype: int64

In [24]:
#6
#Mapping "DM" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['DM']	=	data_frame['DM'].map(map_output)

#data_frame['DLP']

In [25]:
data_frame['DM'].value_counts(dropna=False)

 0     551
 1     283
-20      1
Name: DM, dtype: int64

In [26]:
data_frame['Physical Exercise'].value_counts(dropna=False)

no     764
yes     62
NaN      9
Name: Physical Exercise, dtype: int64

In [27]:
#7
#Mapping "Physical Exercise" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Physical Exercise']	=	data_frame['Physical Exercise'].map(map_output)

#data_frame['Physical Exercise']

In [28]:
data_frame['Physical Exercise'].value_counts(dropna=False)

 0     764
 1      62
-20      9
Name: Physical Exercise, dtype: int64

In [29]:
data_frame['Family History'].value_counts(dropna=False)

no     551
yes    277
NaN      7
Name: Family History, dtype: int64

In [30]:
#8
#Mapping "Family History" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Family History']	=	data_frame['Family History'].map(map_output)

#data_frame['Family History']

In [31]:
data_frame['Family History'].value_counts(dropna=False)

 0     551
 1     277
-20      7
Name: Family History, dtype: int64

In [32]:
data_frame['Drug History'].value_counts(dropna=False)

yes    506
no     301
NaN     28
Name: Drug History, dtype: int64

In [33]:
#9
#Mapping "Drug History" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Drug History']	=	data_frame['Drug History'].map(map_output)

#data_frame['Drug History']

In [34]:
data_frame['Drug History'].value_counts(dropna=False)

 1     506
 0     301
-20     28
Name: Drug History, dtype: int64

In [35]:
data_frame['Psychological Stress'].value_counts(dropna=False)

no     662
yes    158
NaN     15
Name: Psychological Stress, dtype: int64

In [36]:
#10
#Mapping "Psychological Stress" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Psychological Stress']	=	data_frame['Psychological Stress'].map(map_output)

#data_frame['Psychological Stress']

In [37]:
data_frame['Psychological Stress'].value_counts(dropna=False)

 0     662
 1     158
-20     15
Name: Psychological Stress, dtype: int64

In [38]:
data_frame['Chest Pain'].value_counts(dropna=False)

yes    488
no     344
NaN      3
Name: Chest Pain, dtype: int64

In [39]:
#11
#Mapping "Chest Pain" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Chest Pain']	=	data_frame['Chest Pain'].map(map_output)

#data_frame['Psychological Stress']

In [40]:
data_frame['Chest Pain'].value_counts(dropna=False)

 1     488
 0     344
-20      3
Name: Chest Pain, dtype: int64

In [41]:
data_frame['Dyspnea'].value_counts(dropna=False)

no     543
yes    290
NaN      2
Name: Dyspnea, dtype: int64

In [42]:
#12
#Mapping "Dyspnea" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Dyspnea']	=	data_frame['Dyspnea'].map(map_output)

#data_frame['Dyspnea']

In [43]:
data_frame['Dyspnea'].value_counts(dropna=False)

 0     543
 1     290
-20      2
Name: Dyspnea, dtype: int64

In [44]:
data_frame['Palpitation'].value_counts(dropna=False)

no     681
yes    149
NaN      5
Name: Palpitation, dtype: int64

In [45]:
#13
#Mapping "Palpitation" feature
map_output = {"yes" : 1, "no" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['Palpitation']	=	data_frame['Palpitation'].map(map_output)

#data_frame['Palpitation']

In [46]:
data_frame['Palpitation'].value_counts(dropna=False)

 0     681
 1     149
-20      5
Name: Palpitation, dtype: int64

In [47]:
data_frame['ECG'].value_counts(dropna=False)

abnormal    519
normal      280
NaN          36
Name: ECG, dtype: int64

In [48]:
#14
#Mapping "ECG" feature
map_output = {"abnormal" : 1, "normal" : 0, None:-20}

#	Setting	the	map	to	the	data_frame 
data_frame['ECG']	=	data_frame['ECG'].map(map_output)

#data_frame['ECG']

In [49]:
data_frame['ECG'].value_counts(dropna=False)

 1     519
 0     280
-20     36
Name: ECG, dtype: int64

In [50]:
data_frame.isnull().sum()

Age                     0
Sex                     0
Smoking                 0
HTN                     0
DLP                     0
DM                      0
Physical Exercise       0
Family History          0
Drug History            0
Psychological Stress    0
Chest Pain              0
Dyspnea                 0
Palpitation             0
ECG                     0
IHD-HeartAttack         0
dtype: int64

In [51]:
x=data_frame.values
for i in range(len(data_frame)):
    print(x[i])

[65.  1.  0.  1.  0.  1.  0.  0.  1.  0.  1.  0.  0.  1.  1.]
[48.  1.  0.  1.  0.  1.  0.  0.  1.  0.  1.  0.  0.  1.  1.]
[80.  1.  2.  1.  0.  1.  1.  0.  1.  0.  0.  0.  0.  1.  1.]
[67.  1.  1.  1.  0.  0.  0.  0.  1.  0.  1.  1.  0.  1.  1.]
[55.  1.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  1.  1.]
[85.  2.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.  1.]
[ 80.   1.   2.   1.   0.   0.   1.   0.   0.   0.   1.   0.   0. -20.
   0.]
[ 75.   2.   0.   0.   0.   0.   0.   1. -20.   0.   0.   1.   0.   1.
   1.]
[ 26.   1.   0.   0.   0.   0.   0.   0.   0.   1.   1.   1.   1. -20.
   1.]
[ 69.   1.   0.   0.   0.   0.   0.   0. -20.   0.   0.   1.   0.   1.
   1.]
[ 65.   1.   0.   1.   0.   0.   0.   1. -20.   0.   1.   1.   0.   1.
   1.]
[ 50.   1.   0.   1.   0.   1.   0.   1. -20.   0.   1.   0.   0. -20.
   0.]
[ 63.   1.   2.   1.   0.   1.   0.   0. -20.   0.   1.   0.   0.   1.
   1.]
[ 62.   1.   1.   1.   0.   0.   0.   0. -20.   0.   0.   0.   0.   1.
   1.]
[ 63

[35.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.  1.]
[25.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.]
[42.  1.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.]
[48.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[60.  1.  2.  0.  1.  1.  0.  0.  1.  1.  0.  0.  0.  1.  1.]
[54.  2.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.  1.  0.  0.]
[70.  1.  2.  1.  1.  0.  0.  1.  1.  1.  1.  1.  1.  0.  0.]
[33.  1.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
[45.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[45.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
[46.  2.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.  1.  0.  0.]
[52.  1.  0.  1.  0.  1.  0.  1.  1.  0.  0.  0.  0.  0.  0.]
[42.  1.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  1.  0.  0.]
[48.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[40.  1.  0.  1.  0.  0.  0.  0.  1.  0.  1.  1.  1.  0.  0.]
[38.  2.  0.  0.  0.  0.  0.  1.  1.  0.  1.  1.  0.  0.  0.]
[52.  1.

In [52]:
data_frame.head()

Age  Sex  Smoking  HTN  DLP  DM  Physical Exercise  Family History  \
0  65.0    1        0    1    0   1                  0               0   
1  48.0    1        0    1    0   1                  0               0   
2  80.0    1        2    1    0   1                  1               0   
3  67.0    1        1    1    0   0                  0               0   
4  55.0    1        1    1    0   0                  0               0   

   Drug History  Psychological Stress  Chest Pain  Dyspnea  Palpitation  ECG  \
0             1                     0           1        0            0    1   
1             1                     0           1        0            0    1   
2             1                     0           0        0            0    1   
3             1                     0           1        1            0    1   
4             0                     0           1        1            0    1   

   IHD-HeartAttack  
0                1  
1                1  
2                1  
3                1  
4                1

In [57]:
#suffle the data set
#np.random.seed(41)
df = data_frame.reindex(np.random.permutation(data_frame.index))
df.reset_index(inplace=True,drop=True)

In [58]:
df.head()

Age  Sex  Smoking  HTN  DLP  DM  Physical Exercise  Family History  \
0  45.0    2        0    1    0   1                  0               0   
1  50.0    1        0    0    0   0                  0               0   
2  29.0    1        0    0    0   0                  0               0   
3  60.0    2        0    1    0   1                  0               0   
4  43.0    1        0    1    0   0                  0               0   

   Drug History  Psychological Stress  Chest Pain  Dyspnea  Palpitation  ECG  \
0           -20                     0           1        1            0  -20   
1             0                     0           1        1            0    1   
2             0                     0           0        0            0    0   
3             0                     0           0        0            0    1   
4             1                     1           0        0            1    0   

   IHD-HeartAttack  
0                0  
1                1  
2                0  
3                1  
4                0

In [59]:
df.shape

(835, 15)

In [60]:
X = df.values

In [61]:
#Impute with mean all 0 readings(replacing messing value)

fill_0 = Imputer(missing_values=-20, strategy="median", axis=0)

#fill_0 = Imputer(missing_values=0, strategy="mean", axis=0)

X = fill_0.fit_transform(X)

/home/sakib/.local/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [63]:
for i in range(len(df)):
    print(X[i])

[45.  2.  0.  1.  0.  1.  0.  0.  1.  0.  1.  1.  0.  1.  0.]
[50.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  1.  1.]
[29.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[60.  2.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
[43.  1.  0.  1.  0.  0.  0.  0.  1.  1.  0.  0.  1.  0.  0.]
[57.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
[62.  1.  0.  1.  0.  1.  0.  0.  1.  0.  0.  0.  0.  1.  1.]
[30.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
[38.  1.  2.  1.  0.  0.  0.  0.  1.  0.  1.  0.  0.  1.  1.]
[65.  2.  0.  1.  0.  1.  0.  0.  1.  0.  1.  1.  0.  1.  1.]
[45.  2.  0.  1.  0.  0.  0.  0.  1.  0.  1.  0.  0.  1.  1.]
[44.  2.  0.  1.  0.  1.  0.  0.  1.  1.  0.  0.  0.  0.  0.]
[26.  2.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  1.  0.  0.]
[38.  2.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
[50.  1.  1.  0.  0.  0.  0.  1.  1.  1.  0.  1.  0.  1.  1.]
[32.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[60.  1.

[75.  1.  2.  1.  1.  0.  0.  1.  1.  0.  0.  1.  0.  1.  1.]
[65.  2.  0.  1.  0.  1.  0.  0.  1.  0.  0.  1.  1.  1.  1.]
[55.  1.  1.  0.  0.  0.  0.  0.  1.  0.  1.  1.  1.  1.  1.]
[24.  1.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  1.  1.]
[35.  1.  1.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.  1.]
[42.  1.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  1.  1.  1.]
[40.  1.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  1.]
[38.  1.  0.  0.  0.  1.  0.  0.  1.  1.  0.  1.  1.  1.  1.]
[55.  1.  1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.  1.]
[60.  1.  1.  1.  0.  1.  0.  0.  1.  0.  1.  0.  0.  1.  1.]
[70.  1.  1.  1.  0.  0.  0.  0.  1.  1.  0.  1.  0.  1.  1.]
[70.  1.  2.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.  1.]
[54.  1.  0.  1.  0.  0.  0.  1.  1.  1.  1.  0.  0.  1.  1.]
[46.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[65.  1.  0.  1.  0.  1.  0.  0.  1.  0.  1.  0.  0.  1.  1.]
[65.  1.  2.  0.  0.  1.  0.  0.  1.  0.  1.  0.  0.  0.  0.]
[40.  1.

In [64]:
with open('data_v2_clean_ecg.tab', 'w') as datafile:    
    writer = csv.writer(datafile, delimiter='\t')
    for index in range(len(X)):
        writer.writerow(X[index])

In [72]:
dataframe = pd.read_csv('data_v2_clean_ecg.tab', sep='\t')
dataset = dataframe.values
len(dataframe)

835

In [73]:
dataframe.shape

(835, 15)

In [74]:
dataframe.head()

Age  Sex  Smoking  HTN  DLP   DM  Physical_Exercise  Family_History  \
0  45.0  2.0      0.0  1.0  0.0  1.0                0.0             0.0   
1  50.0  1.0      0.0  0.0  0.0  0.0                0.0             0.0   
2  29.0  1.0      0.0  0.0  0.0  0.0                0.0             0.0   
3  60.0  2.0      0.0  1.0  0.0  1.0                0.0             0.0   
4  43.0  1.0      0.0  1.0  0.0  0.0                0.0             0.0   

   Drug_History  Psychological_Stress  Chest_Pain  Dyspnea  Palpitation  ECG  \
0           1.0                   0.0         1.0      1.0          0.0  1.0   
1           0.0                   0.0         1.0      1.0          0.0  1.0   
2           0.0                   0.0         0.0      0.0          0.0  0.0   
3           0.0                   0.0         0.0      0.0          0.0  1.0   
4           1.0                   1.0         0.0      0.0          1.0  0.0   

   IHD-HeartAttack  
0              0.0  
1              1.0  
2              0.0  
3              1.0  
4              0.0